#!/usr/bin/env python
import dbus
from sys import argv

def resolve_phone(number):
  tryme = 'Cell Phone', 'Work phone', 'Phone', 'Home phone'
  for field in tryme:
    x = contacts.Query({field:number})
    query = getDbusObject (bus, "org.freesmartphone.opimd", x, "org.freesmartphone.PIM.ContactQuery")
    if query.GetResultCount():
      result = query.GetResult()
      try:
        name = result['Name']
        sn = result['Surname']
        if sn:
          name = name + " " + sn
        return name
      except:
  return "nothing"

def getDbusObject (bus, busname , objectpath , interface):
  dbusObject = bus.get_object(busname, objectpath)
  return dbus.Interface(dbusObject, dbus_interface=interface)

bus = dbus.SystemBus()

messages = getDbusObject (bus, "org.freesmartphone.opimd", "/org/freesmartphone/PIM/Messages", "org.freesmartphone.PIM.Messages")
contacts = getDbusObject (bus, "org.freesmartphone.opimd", "/org/freesmartphone/PIM/Contacts", "org.freesmartphone.PIM.Contacts")

for number in argv[1:]:
  print number+': '+resolve_phone(number)

if len(argv)==1:
  print "usage: "+argv[0]+ ' number'
  print 'e.g. '+argv[0]+' 663123456'
